#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jul  9 14:21:22 2018

@author: mofassir
"""
import random
class Hashtags():
    ht_list=['TeenChoice',
 'Day379',
 'London',
 'CanadaDay',
 'jimin',
 'GetWellSoonXuanyi',
 'jaewin',
 'kookmin',
 'Bot',
 'publichealth',
 'ChoiceAnimatedTVShow',
 'deobiselcaday',
 'reliable',
 'ChoiceFandom',
 'JIMIN',
 'DLPlive',
 'DungeonMeshi',
 'epic',
 'GOT7',
 'EYESONYOUinTOR',
 'BeStrongErick',
 'NowPlaying',
 'KangDaniel',
 'PartyChilensisFtNiallEnChile',
 'immigration',
 'WeMissYouJimin',
 'kaisoo',
 'mebis',
 'COL',
 'adulting',
 'BlockedAndReported',
 '4thofJuly2018',
 'shocked',
 'xxxtentacion',
 'ApplePay',
 'TeenChioce',
 'WeLoveYouAriana',
 'DCApologize',
 'dogsoftwitter',
 'GainWithCandy',
 'ct',
 'LMS',
 'OnThisDay',
 '정우',
 'GoPackGo',
 'ASentenceBeforeSleep',
 'Batman50',
 'ToysRus',
 'Lacombe',
 'IndieGame',
 'CreedII',
 'EfinSecsyClub',
 'RUNBTS',
 'ThingsIHate',
 'TheVoicenotesTour',
 'StreamerNetwork',
 'racist',
 'saveshadowhuntere',
 'EXO',
 'Underbrush',
 'MORPinoyBiga10',
 'MakersHour',
 'WorldCup18',
 'HAPPYHYUKDAY',
 'oldyoutube',
 'SaveShadowhunters',
 'Bruin',
 'DogBeach',
 'housekinokuni',
 'HeatWave2018',
 'yngUPDATE',
 'SDLive',
 'YIAYart',
 '4thOfJuly',
 'np',
 'naturelovers',
 'SS7Manila',
 'swschilloutCORPUSCHRISTI',
 'ARMYSeIcaDay',
 'Doom',
 'drivetimesessions',
 'africatweetchat',
 'MumbaiBridgeCollapse',
 'SecondCivilWar',
 'Iceland',
 'sadgirls',
 'loveisland',
 'famu22',
 'unfollowed',
 'CampNaNoWriMo',
 'gettingbetterallthetime',
 'ridicula',
 'Fortnite',
 'NickixHndrxxTour',
 '휘인아_사랑해',
 'beogradzivi',
 'mewtwo']
    def __init__(self):
        print('Hashtag Corpus initialized')
    def getHashtag(self):
        return self.ht_list[random.randint(0,len(self.ht_list)-1)]